### ISSUE TITLE
Flash Player Settings Unclickable

### ISSUE THREAD

**Issue by joekur** [jwagener-soundcloud/recorder.js#10]
I'm finding a problem when asked to allow recorderjs access to my microphone (tried in chrome and firefox). The flash player settings box is completely unclickable/unresponsive. This is reproducible in the example linked to in the readme http://dl.dropbox.com/u/12477597/Permanent/recorder.js/examples/example-1.html.

**Comment by jwagener** [comment]
It should be clickable after roughly a second.

This is a click-hijack protection by the Adobe Flash plugin. The button will be clickable once the security panel was fully visible for sometime. There is no workaround for this as far as I know except for showing the security panel right away on page load instead of showing it after a user action (hitting record link/button).

**Comment by joekur** [comment]
Unfortunately not for me! Neither Chrome nor Firefox, and I've tried on a few different Macs (no windows machine to test on right now).

**Comment by joekur** [comment]
I found that this was a bug with flash player / Lion http://forums.adobe.com/thread/880967
That was over a year ago though. I'm surprised if that bug still hasn't been fixed.

**Comment by joekur** [comment]
Okay, it looks like it's still an issue with some macs https://bugbase.adobe.com/index.cfm?event=bug&id=2942091
So probably not an issue with recorderjs.
