### ISSUE TITLE
trying to use sampling rate 8khz instead of 44khz

### ISSUE THREAD

**Issue by dasmod** [jwagener-soundcloud/recorder.js#13]
Hi, 

Because of big file sizes - we are trying to record 8khz audios using recorder.js
We changed the sample rate on recorder.as to 8khz and compiled the code.

The problem we are experiencing is, the recorded file is 8khz but the audio content is ~4x faster.

Is there a way to use recorder.js with 8khz sample rate?

**Comment by jwagener** [comment]
Does this affect only the audio when playing it back using Recorder.play() or also the actual wave file once it's uploaded?

**Comment by dasmod** [comment]
This only happens for recorder.play(). Audio plays normal on media players.

On 17 Eki 2012, at 14:37, Johannes Wagener notifications@github.com wrote:

Does this affect only the audio when playing it back using Recorder.play()
or also the actual wave file once it's uploaded?

—
Reply to this email directly or view it on
GitHubhttps://github.com/jwagener/recorder.js/issues/13#issuecomment-9524184.

**Comment by jwagener** [comment]
the problem is that flash.media.Sound which is used to playback the recording expects a 44.1 sample rate.
I've adjusted the playSampleDataHandler to take the sampleRate into consideration and write the samples multiple times if necessary. but this means that there will be a slight down pitch when playing this back.

Let me know if you have a better solution for this.

The change is pushed in v1.11.

**Comment by dasmod** [comment]
Thanks for the quick feedback.
Ok, we will try the new version asap.
